### ISSUE TITLE
changes with get throws error 

### ISSUE THREAD

**Issue by note89** [hamiltop/rethinkdb-elixir#107]
```
       own_feed_changes =
          table("notification_feeds")
          |> get(own_feed)
          |> changes()
          |> DB.run
```

```
[debug] > leave {:badarg, [{:erlang, :hd, [[]], []}, {RethinkDB.Response, :parse, 3, [file: 'lib/rethinkdb/response.ex', line: 55]}, {App.NotificationChannel, :handle_info, 2, [file: 'web/channels/notification_channel.ex', line: 212]}, {Phoenix.Channel.Server, :handle_info, 2, [file: 'lib/phoenix/channel/server.ex', line: 242]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 615]}, {:gen_server, :handle_msg, 5, [file: 'gen_server.erl', line: 681]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}]}
[error] GenServer #PID<0.619.0> terminating
** (ArgumentError) argument error
    :erlang.hd([])
    (rethinkdb) lib/rethinkdb/response.ex:55: RethinkDB.Response.parse/3
    (app) web/channels/notification_channel.ex:212: App.NotificationChannel.handle_info/2
    (phoenix) lib/phoenix/channel/server.ex:242: Phoenix.Channel.Server.handle_info/2
    (stdlib) gen_server.erl:615: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:681: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

running 
`Running rethinkdb 2.3.4~0wily (GCC 5.2.1)...`

**Comment by norpan** [comment]
I had a similar error with #131

**Comment by norpan** [comment]
Everything seems to work if you just remove line 55 in lib/rethinkdb/response.ex but I don't know what other effects that could have of course. Should I make a pull request? Is this project actively maintained?
